theme:
  name: 'material'
  language: zh
site_name: 郭睿明的小屋
site_url: http://guoruiming.com
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mermaid2

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
copyright: 'Copyleft. All wrongs reversed.<br/><a href="https://beian.miit.gov.cn">冀ICP备2021025718号</a>'
