theme:
  name: "material"
  custom_dir: overrides
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - content.action.edit
    # - header.autohide
  favicon: assets/images/favicon.ico
  icon:
    logo: material/book
    repo: fontawesome/brands/github
  # palette:
  #   # Palette toggle for light mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     toggle:
  #       icon: material/brightness-7
  #       name: Switch to dark mode

  #   # Palette toggle for dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     toggle:
  #       icon: material/brightness-4
  #       name: Switch to light mode

site_name: 郭睿明的小屋
site_url: http://guoruiming.com

markdown_extensions:
  - admonition
  - nl2br
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink
  - pymdownx.highlight:
      use_pygments: false
  # - codehilite:
  #     guess_lang: false
  #     linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  # - pymdownx.betterem:
  #     smart_enable: all
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
        # emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
        # emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
        # emoji_generator: !!python/name:pymdownx.emoji.to_awesome
        # emoji_generator: !!python/name:pymdownx.emoji.to_alt


  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

repo_url: https://github.com/dandelight/dandelight.github.io
repo_name: dandelight/dandelight.github.io

plugins:
  - search:
      lang:
        - en
        - zh
  - tags
  - git-revision-date
  - callouts
  # - mermaid2
  # feature of callouts plugin is covered by obsidian-support plugin
  # but it is unstable
  # - obsidian-support

extra_css:
  - https://npm.elemecdn.com/@highlightjs/cdn-assets@11.8.0/styles/default.min.css
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/config.js # 必须添加在 MathJax 之前
  - https://npm.elemecdn.com/mathjax@3/es5/tex-mml-chtml.js
  - https://npm.elemecdn.com/@highlightjs/cdn-assets@11.8.0/highlight.min.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6 # No need to polyfill
  # - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js # Use built-in mermaid plugin

copyright: 'Copyleft. All wrongs reversed.<br/><a href="https://beian.miit.gov.cn"><img alt="冀ICP备2021025718号" src="https://img.shields.io/badge/%E5%86%80ICP%E5%A4%87-2021025718%E5%8F%B7-blue"></img></a> <a href="http://www.beian.gov.cn/"><img alt="川公安网备51012202001103号" src="https://img.shields.io/badge/%E5%B7%9D%E5%85%AC%E5%AE%89%E7%BD%91%E5%A4%87-51012202001103%E5%8F%B7-blue"></img></a>  <img alt="GitHub last commit" src="https://img.shields.io/github/last-commit/Dandelight/dandelight.github.io?color=blue">'
